version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - keybase_bot_mongo:/data/db
        

  keybase_bot:
    build: .
    image: docker.pkg.github.com/noah-witt/keybase-meme-chat/srv:0.0.1
    restart: always
    ports:
      - 127.0.0.1:8484:8080
    env_file:
      - example.env
      - .env
    links:
      - "mongo:db"
volumes:
  keybase_bot_mongo: